### ISSUE TITLE
Clementine (Nightly Windows build) stuck with "Updating library 0&#37;"

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#3064]
_From [virtualshuric](https://code.google.com/u/virtualshuric/) on July 19, 2012 10:49:28_

What steps will reproduce the problem? 1. Start Clementine post-1.0.1-nightly on Windows (clean install without profile or upgrade from 1.0.1)
2. Wait a little to get sure, that "updating library" isn't progressing What is the expected output? What do you see instead? With nightly build Clementine stucks at 0&#37; progress when updating library(updating, rescanning or initial scan). Old library data is accessible though. With fresh profile library is empty. 

Integrity check and database backup pass successfully (parallel to updating library). Setting ratings on existing songs works fine (ratings are persistent between app restarts)

"clementine-tagreader.exe" sits in process list (with constant 0&#37; CPU and memory usage) - I don't know if it's intended behavior. Also Clementine crashes on exit. What version of the product are you using? On what operating system? 1. Clementine nightly-builds (w/podcasts and moodbars)
2. OS: Windows 7, 32-bit

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=3064_

**Comment by sabret00the** [comment]
Not sure if this helps but got this from the terminal when it stuck
'''15:31:48.069 DEBUG TagReader:793                    Setting FMPSFrame: "FMPS_Rating" ,  "1" 
15:31:48.080 DEBUG LibraryWatcher:345               "/media/sabret00the/My Passport/__music/My Music/Army Of The Pharaohs/aotp - dont cry.mp3" changed 
15:31:48.081 DEBUG TagReader:119                    Reading tags from "/media/sabret00the/My Passport/__music/My Music/Army Of The Pharaohs/aotp - dont cry.mp3" 
15:31:48.081 DEBUG TagReader:420                    Parsing FMPSFrame "FMPS_Rating" ,  "1" 
15:31:48.082 DEBUG _MessageReplyBase:24             Waiting on ID 2 
15:31:48.166 DEBUG MessageReply<MessageType>:90     Releasing ID 1 (finished) 
15:31:49.608 DEBUG MainWindow:1324                  position 10 scrobble point 108 status 0 
15:31:59.608 DEBUG MainWindow:1324                  position 20 scrobble point 108 status 0 
15:32:09.608 DEBUG MainWindow:1324                  position 30 scrobble point 108 status 0 
15:32:19.608 DEBUG MainWindow:1324                  position 40 scrobble point 108 status 0 
15:32:28.600 DEBUG Playlist:1656                    Setting metadata for  QUrl( "file:///media/sabret00the/My Passport/__music/My Music/Army Of The Pharaohs/AOTP - Bust 'em In featuring Reef The Lost Cauze, Apathy, Celph Titled.mp3" )  to "Army Of The Pharaohs" "Bust 'em In (Feat. Reef The Lost Cauze, Apathy, Celph Titled)" 
15:32:28.707 DEBUG Playlist:1656                    Setting metadata for  QUrl( "file:///media/sabret00the/My Passport/__music/My Music/Army Of The Pharaohs/AOTP - Bust 'em In featuring Reef The Lost Cauze, Apathy, Celph Titled.mp3" )  to "Army Of The Pharaohs" "Bust 'em In (Feat. Reef The Lost Cauze, Apathy, Celph Titled)" 
15:32:29.608 DEBUG MainWindow:1324                  position 50 scrobble point 108 status 0 
15:32:39.608 DEBUG MainWindow:1324                  position 60 scrobble point 108 status 0 
15:32:49.610 DEBUG MainWindow:1324                  position 70 scrobble point 108 status 0 
15:32:59.608 DEBUG MainWindow:1324                  position 80 scrobble point 108 status 0 
15:33:03.869 DEBUG Database:584                     Starting database integrity check 
15:33:04.387 DEBUG Database:645    ''''

**Comment by jerobarraco** [comment]
hmm , i tried compiling the app myself, and it _seems_ to work fine. but only compiling from source. 
i tried using valgrind and i think there where a memory corruption somewhere but im not sure. Maybe it works well because i'm compiling with qt 5.4 sdk.
the process pool seems weird to me, some pointers might get deleted right after they get initialized, not sure. (i dont remember well because i did it some time ago)
i think each process pool's pid (or id) gets stored in the struct to later see which one replied. When i debugged, all the proccesses got the SAME id, and the db got stuck. as soon as i forcekill one of those processes, clem spawened some more tagreaders and worked fine...
i dont get why you dont use qt's pools features http://qt-project.org/doc/qt-4.8/qtconcurrent.html
(yes i know multiprocess!=multithread but at least it could leverage the pool part (which smells fishy to me (imvho)))

**Comment by sabret00the** [comment]
On the current nightly, it will freeze on Updating Library reliably when switching hard disks. Currently my music is stored on two separate disks (local partition and external hard drive).

It seems to link to https://github.com/clementine-player/Clementine/issues/4851

**Comment by nmjbhoffmann** [comment]
OS: Linux Mint 17.1 x64
Current Build: Version 1.2.3-1158-ge7e3ab1 (e7e3ab1)

I also seem to find an issue with it going into an "Updating Library" loop, I don't get any related debug information when running from console, a reliable way for me to run into this issue is if I **change the rating of a song that's currently playing**.

This is running off a network mounted volume and off a FLAC file type, though it seems to go into this loop after a **few minutes of playing without any intervention**.

The update loop also prevents Clementine from exiting which is expected.

**Comment by jerobarraco** [comment]
This is still happening. I'm on Version 1.2.3-1280-g10860b7
Any idea how can i help with this? Is getting really annoying.
I can't edit songs, and i can't either exit.

**Comment by jerobarraco** [comment]
i tried to run valgrind on it, but is SO slow... i got it loading and playing. but still haven't got stuck...
each time it loads it shows some errors.
I had some modules not compiled because the dependencies are a little too much for me... i tried to compile one or two more to see if that triggers something. 

Output is http://pastebin.com/34tgsAct
Valgrind said http://pastebin.com/sija9qJu
CMakeCache http://pastebin.com/4NqEYPXf

**Comment by jerobarraco** [comment]
I tired again, compiled with everything, and ran a valgrind until it got stuck.
this are the results. Though valgrind didn't notify me when the lib got stuck... so maybe (and most probably) this is a side-effect of another thing.

Valgrind said http://pastebin.com/2mEnX1df
Output was http://pastebin.com/xRx8faeF
CMakecache is http://pastebin.com/vk5dqC0L

I recall once i tried debugging this, and the client-id for the tagreader on the communication library that used that weird google thing seems to have gotten overriden with an older id, every tagreader seemed to have the same id, an invalid one. though im not sure.

**Comment by sabret00the** [comment]
So I got a new laptop and hoped the issue would be one of the past. I've now moved my library to my NAS but despite that, I'm still seeing issues with it getting stuck. I think since I'm now on Ubuntu 64 bit it's no longer preventing Clementine from closing. But it remains frustrating. I wonder if @davidsansome has any insight on this long-standing bug?

**Comment by jerobarraco** [comment]
after this #5129 i haven't seen the bug again.
i even have the "monitor library for changes" option on.

**Comment by sabret00the** [comment]
I'm still seeing this.

**Comment by jerobarraco** [comment]
thats bad. maybe this can help, but have you tried disabling to monitor folders? that helped me once
http://screencloud.net/v/fD61

**Comment by sabret00the** [comment]
Stopping it from monitoring changes only hides the problem. You can tell because album art stops changing.

**Comment by mwmza** [comment]
I got this bug now after updating to Clementine 1.3 on Ubuntu 14.04. I tried re-reading the library but after it's done it will go into "Updating 0%" forever, not changing covers, and four (!) instances of "clementine tag reader" are shown in the system processes each using 1,1 MB of RAM.

**Comment by quantverse** [comment]
Same issue here (Clementine 1.3.1 on Ubuntu 14.04). Definitely related to modifying mp3 files (ID3 tags/rating), most likely when one of tracks being modified is currently playing. Probably deadlock?

There are errors in log file like this one:
```
22:41:02.441 ERROR logging:54                       Source ID 638 was not found when attempting to remove it
```

**Comment by quantverse** [comment]
Deleting rating of a song currently playing:

```
23:13:41.898 DEBUG TagReader:795                    Saving song rating tags to "/xxx/yyy/zzz/06 Descarga Zamot.mp3" 
23:13:41.901 DEBUG TagReader:863                    Setting FMPSFrame: "FMPS_Rating" ,  "0" 
23:13:41.922 DEBUG MessageReply<MessageType>:90     Releasing ID 637 (finished) 
23:13:41.923 WARN  unknown                          QWaitCondition::wakeAll(): mutex lock failure: Invalid argument 
23:13:41.923 DEBUG LibraryWatcher:606               Subdir "/xxx/yyy/zzz" changed under directory "/xxx" id 1 
23:13:44.630 DEBUG LibraryWatcher:343               "/xxx/yyy/zzz/06 Descarga Zamot.mp3" changed 
23:13:44.630 DEBUG _MessageReplyBase:24             Waiting on ID 638
```
After this, the library gets stuck in "Updating library" forever. I can play songs, but I cannot modify tracks any longer.

It seems easy to reproduce, happens almost all the time! It seems like there is some deadlock related to the fact the file is modified, played and monitored at the same time?

Please fix, this is really annoying.

**Comment by quantverse** [comment]
I can confirm that if I disable the `Monitor the library for changes` option problem disappears. I will use this as a workaround for now.

**Comment by jerobarraco** [comment]
i get really annoyed by this issue.
i tried to debug it once, i'm not a genius and the protobuff bloat makes it harder to see.

BUT as far as i could see, the thing is this:
it creates workers and stores some sort of pointer to its info. but, at some point the worker crashes and as it makes use of some sort of pointer auto-delete functionality, at that point, all the references are changed to the same worker, or to an invalid worker.
so when it tries to command the workers it always fails. That's why under specific conditions, if you kill the only worker that is being referenced, more workers are created though the other workers are still alive. 
usually those workers end up being orphaned.

**Comment by mwmza** [comment]
> I can confirm that if I disable the Monitor the library for changes option problem disappears. I will use this as a workaround for now.
This.

**Comment by quantverse** [comment]
Hmm, unfortunately there are problems even with `Monitor the library for changes` disabled. I have modified comment of a song (not currently playing one) and now I cannot edit any other track information. The window "Edit track information" is stuck with "Loading tracks..." message indefinitely.

**Comment by calltheninja** [comment]
I found a fix for this after googling for a while and not finding this suggestion. My suspicion was that Clementine was choking on some file it couldn't access or do something important with. I tried disabling "update library" etc. This is on Ubuntu 14.04 x64 with Clementine 1.3.1. Here's the fix that worked for me:

1. Fix permissions on all local music files
I just did the command below to make sure any user/program on the system could access the files:
sudo chmod -R 777 /directory/to/music

2. Fix weird filenames, UTF-8 characters, etc
Install the package "detox" from the Ubuntu repos or download it from the link below:
https://sourceforge.net/projects/detox/files/detox/
Run the command:
detox -r /path/to/music
You can add a -n to see what it would change (dry run).

3. Restart clementine
Kill clementine completely and open it again.

This got it working for me, hopefully it works for you!

**Comment by naraesk** [comment]
The workaround didn't work for me. Still the same problem (ratings get lost + 0% on updating library)

**Comment by sabret00the** [comment]
Just to explain @naraesk, once the background services get stuck, Clementine is unable to update ratings and generally everything just gets broken. The work around above isn't a one size fits all as it's a genuine bug that @davidsansome or @hatstand hopefully will get around to looking at sooner or later. Anyway, when things get stuck, all of the ratings are only stored to file and not to the mp3s themself and thus any time Clementine has a heart attack and poops the bed, those ratings are lost.

**Comment by naraesk** [comment]
Well, then I'm not sure if my bug (#5429) is really the same. It's not only that ratings/metadata will not be updated correctly, but 2 years old ratings just get lost by accident, even if the files were not played/opened/edited.

**Comment by sabret00the** [comment]
Remove and re-add your library folders if you're sure that all ratings are already sync'd to your files.

**Comment by Ketchup901** [comment]
I'm getting a very similar issue. For seemingly no reason, Clementine now displays on start up "Updating library", followed by a percentage that varies (usually 33-34%). Also, Unicode characters don't display. [url=http://pix.toile-libre.org/upload/original/1477210139.png]This[/url] is how they're displayed.
This is present even after deleting my config files and reinstalling Clementine.
I tried doing what @calltheninja said but it didn't work.

64-bit version on Arch Linux

**Comment by reticulatus** [comment]
I am having the same problem using Version 1.3.1-228-gd9b3a93 (from me-davidsansome) on Mint 18 64-bit. 
After starting Clementine I am able to edit some ID3 tags for a while, but then inevitably it will get stuck with "Loading tracks" message. I have tried the various suggestions given above, but none of them have had stopped the problem from occurring. 
When the problem last occurred, the following debug message was output:
10:28:59.144 DEBUG _MessageReplyBase:24             Waiting on ID 362 
This is very frustrating as Clementine has all the functionality that I was looking for, but this bug makes it very difficult to work with as I have to keep killing and restarting it before I can edit any more tags.

**Comment by capponz** [comment]
same issue here Clementine Version 1.3.1 on Mint 16.04. please fix
777 and detox did not work for me.

**Comment by Ketchup901** [comment]
Actually, my issue was fixed by generating proper locales, in my case I needed to att ja_JP.UTF8.

**Comment by jerobarraco** [comment]
‎Interesting, I have lots of songs with Asian names (Chinese Japanese and Korean) as well as some Russian. But I don't know if I have the locals                                                                                                                                                                                                                 From: Ketchup901Sent: Saturday, April 8, 2017 05:48To: clementine-player/ClementineReply To: clementine-player/ClementineCc: Nande!; CommentSubject: Re: [clementine-player/Clementine] Clementine (Nightly Windows build) stuck with "Updating library 0&#37;" (#3064)Actually, my issue was fixed by generating proper locales, in my case I needed to att ja_JP.UTF8.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/clementine-player/Clementine","title":"clementine-player/Clementine","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/clementine-player/Clementine"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Ketchup901 in #3064: Actually, my issue was fixed by generating proper locales, in my case I needed to att ja_JP.UTF8."}],"action":{"name":"View Issue","url":"https://github.com/clementine-player/Clementine/issues/3064#issuecomment-292704614"}}}

**Comment by deutrino** [comment]
This seems like it could be multiple bugs rolled into one github issue. If people who've done some debugging see that that's the case, maybe file separate issues and reference this one? This is an annoying problem and it might be more likely fixed if when a dev comes along they don't have to wade through an entire confusing ticket.

**Comment by BobbyWibowo** [comment]
This issue still persists on me. Running Ubuntu 16.04 LTS with Clementine 1.3.1-353-gfcceab3.

I already generated the necessary locales for songs with Japanese characters. Before generating the locales, Clementine indeed kept on failing to load some albums with Japanese characters in their filenames, but after I generated the locales, it could properly load everything.
But if I have "monitor library for changes" enabled in the Preferences, before long the "Loading library 0%" would show up again and the area at the bottom left where it would usually show basic information of the currently playing song would also freeze.
I could play other songs just fine, but that area would remain frozen with information of the last song it played before it froze.
Afterwards I'd also be unable to edit track information because the UI would stuck on "Loading tracks" or something.

**Comment by Matt832** [comment]
Been having the same issue for some time too.  Linux Mint 17.x and Clementine 1.3.1-333-gf854bc5 .  Have not used Clementine for a few months, and decide to use it again as it was easy to control via remote.  Stuck at "updating library 0%" and the remote is not getting current info as to track info.  shows only the initial song played back, along with no album art. Frustrating as I feel Clementine is one of the best players out there.

**Comment by BobbyWibowo** [comment]
Alright, continuation to my previous post, here's my latest settings in Preferences > Music library:
`[x]` Update the library when Clementine starts
`[x]` Monitor library for changes
`[ ]` Save ratings in file tags when possible
`[ ]` Save statistics in file tags when possible
and in the past 7 days or more, it has been working just fine.

At first I thought it had something to do with Last.fm scrobbling but fortunately it wasn't that. I've been scrobbling with that settings as well and it didn't bug out.

Some other details:
- Music directory got chmod 777 for both directories and files.
- UTF-8 locales installed (C.UTF_8 as the system's locale).
- There are a lot of music files with UTF-8 characters in their file names and I could play them just fine as well.

**Comment by shaggyrogers** [comment]
I also had this issue with Clementine 1.3.1-397-gd71651db7, on Ubuntu 17.04 with kernel 4.10. I fixed it by following the advice given by @calltheninja and @BobbyWibowo:

1. cd into your music library folder and run these commands (make sure you know what they do first):
* sudo chown user 
* chmod -R a=r,u+w,a+X *
* detox -r *
2. "detox" any folders in music library path if necessary
3. Uncheck "Save ratings in file tags when possible" and "Save statistics in file tags when possible" in Preferences > Music Library (under Automatic Updating)
4. Restart Clementine.

**Comment by AnthonyWC** [comment]
Quick note: Do NOT use dotex if you have any non-english filename or at least check first by using -n (dry-run).

**Comment by Hlsgs** [comment]
For anyone encountering this, a potential cause is Malwarebytes. It affects v1.3.1, 1.4.0rc1 and the Strawberry fork.

**Comment by pericles-c** [comment]
I'm having this problem with v1.3.1, Windows version, but instead of 0% it gets stuck somewhere in the middle, depending on which folder I choose for my library (usually around 10%). 

Funny thing is, it works fine in other computer with same Clementine and Windows' version, and I have no idea what is happening different. I don't have Malwarebytes installed in any of them.

**Comment by amhainen** [comment]
I'm having this stuck-at-0% issue on Windows with v1.3.1 also. Monitoring is disabled, the songs are on my C:\ drive where Clementine is installed, and I've uninstalled and deleted the .config folder and reinstalled. Clementine works on my same library on another Windows computer, and with the same library o another Linux computer.
