### ISSUE TITLE
"Previous Track" option is always greyed out in KDE Plasma integration

### ISSUE THREAD

**Issue by paul4ig** [clementine-player/Clementine#5571]
OpenSUSE Leap 42.2, KDE Plasma 5.8.3, Clementine 1.3.1

In the KDE window previews / jump lists / Media Player system tray widget there are controls to play/pause, stop, next track, and previous track. These all work except for the "previous track" option which is always greyed out and never works.

**Comment by paul4ig** [comment]
Sometimes this bug also appears in reverse where the previous button is available but the next button is missing when it shouldn't be. Never are both buttons present when they should be on KDE Plasma.

**Comment by arasbill** [comment]
Have you found any solution/work around for this?

**Comment by jiyiiy** [comment]
I can't be sure it's the same/a related issue, but both the previous and the next buttons were always grayed out for me in the KDE Plasma interface media controls (and in playbar2) using the stock Clementine 1.3.11-11 package in Manjaro linux (KDE Plasma 5.11.5).  

When I installed the clementine-git 1.3.1.r405.g790fcff2-1 package from the Arch Linux AUR (source package) though, both buttons work OK, which tells me this issue might either have been fixed, or perhaps had to do with the way stock Clementine was built or linked in Manjaro.

**Comment by alexpolevoy** [comment]
2018, still have this problem in KDE. Not only one of the options is greyed out, but **all** of them are, except _Pause_ and _Stop_. After using one or another, everything except _Stop_ becomes unavailable, including _Play_. I am using daily updated KDE Neon User Edition (based on 16.04).

All of it worked perfectly a month ago, but since then Clementine became unusable with KDE.

**Comment by charliefrance** [comment]
Same here on Fedora 40
