### ISSUE TITLE
The internet services "Last.fm" is lost

### ISSUE THREAD

**Issue by giovannisn** [clementine-player/Clementine#6522]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [ x] I checked the issue tracker for similar issues
- [x ] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x ] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Ubuntu Mate 18.04.03
- Clementine version: 1.4 rc1

### Expected behaviour / actual behaviour
I can't find the intenet service "Last.fm" in "Preferences"
### Steps to reproduce the problem (only for bugs)
I updated my clementine from 1.3 to 1.4, and when I updated it I lost the internet service "Last.fm". I can't find this service in "Preferences", and of course I am not scrobbling my songs.

**Comment by jbroadus** [comment]
Looks like the circleci config for bionic is still using liblastfm-dev instead of the qt5 liblastfm5-dev version.

**Comment by vdheuvel** [comment]
I have the same issue on windows

**Comment by devzsolt** [comment]
same on mac

**Comment by awsms** [comment]
same here, had to downgrade

**Comment by TheUbuntuGuy** [comment]
This was fixed for Debian based builds with https://github.com/clementine-player/Clementine/pull/6525/files#diff-1d37e48f9ceff6d8030570cd36286a61.

It is working for me with the latest build here https://builds.clementine-player.org/ubuntu-bionic/

**Comment by jbroadus** [comment]
For windows, I don't see a lastfm library in the build docker.
For Mac, it's probably just a matter of adding the dependency to the brew list. I can try adding that, but don't have a mac to test on.

**Comment by awsms** [comment]
> This was fixed for Debian based builds with https://github.com/clementine-player/Clementine/pull/6525/files#diff-1d37e48f9ceff6d8030570cd36286a61.
> 
> It is working for me with the latest build here https://builds.clementine-player.org/ubuntu-bionic/

Thanks, grabbed the 1.4.0rc1-99 build and Last.fm is back.

**Comment by awsms** [comment]
> The fix is to create the directory `/home/<user>/.local/share/Last.fm/`. Then scrobbles will work correctly.

That did the trick, thank you!
By the way, is it possible to track favorited songs on Last.fm in Clementine? Or you can only send a "Favorite" signal to Last.fm and that's it?

**Comment by hatstand** [comment]
Fixed for mac.

**Comment by Vanecx** [comment]
> Edit: I can only send a "Now Playing" to last.fm, tracks won't get scrobbled.

I have the same problem since today. This morning I was on Ubuntu 20.04 with Clementine 1.3.1 and it was working correctly. I made a fresh install of Ubuntu 20.04 and it is now Clementine 1.4.0rc, and the problem mentioned above appeared. 

"Now Playing" works, also favoriting a song. But the scrobbles are not saved. Scrobbling from another source also works.

> The fix is to create the directory `/home/<user>/.local/share/Last.fm/`. Then scrobbles will work correctly.

I created the folder as explained here, restarted, unfortunately nothing changed.

**Comment by Vanecx** [comment]
Update : 

I wanted to install Clementine 1.3.1. I went on [the download page](https://www.clementine-player.org/fr/downloads), I downloaded the Xenial version (64bits), but when I opened it, the Software center showed me an error message "Impossible d'installer le fichier : il n'est pas pris en charge" (impossible to install the file, it is not supported). 

I tried with the terminal : 

sudo dpkg -i ~/Téléchargements/clementine_1.3.1-xenial_amd64.deb
sudo apt-get install -f

The installation went fine except... it installed the Version 1.4 rc1 :open_mouth: 

I tried scrobbling nevertheless, and to my surprise, it is actually working normally now. 

So problem solved for me, but I find it rather mysterious :D 

Feel free to ask me anything if you think it might be helpful for other people. Enjoy you day!

**Comment by jsoques** [comment]
I had same issue. Using Xubuntu (Ubuntu 20.04.1 LTS) and Clementine 1.4 rc1 was installed. Only showed 'Scrobbling Now' but not preserving the played record. Tried adding the` /home/<user>/.local/share/Last.fm/` but did not solve. So I did the same thing @Vanecx did, uninstalled clementine 1.4 rc1 and downloaded clementine_1.3.1-xenial_amd64.deb... did:
```
sudo dpkg -i ~/Téléchargements/clementine_1.3.1-xenial_amd64.deb
sudo apt-get install -f
```
ended up with 1.4 rc1 installed and seems to work now. I think the problem is the snap version.

**Comment by jonaski** [comment]
The snap version uses a similar directory structure but it's under ~/snap, but snaps are horrible in general, don't use them. Backup the db and conf file before you uninstall it because it will wipe all the configuration files.

**Comment by eignatenkov** [comment]
Tried this approach with creating the dir, installing 1.3.1 with errors and then doing install -f, it still doesn't scrobble :(

**Comment by jddinneen** [comment]
on Manjaro w/ kernel 5.10, clementine 1.4 rc2, had the same problem but manual creation of the .local cache directory fixed it (though nothing appears in the directory?). No restart required.

**Comment by allhailwesttexas** [comment]
On Ubuntu 21.10, tried creating the `Last.fm` dir to no avail as described in #6829. Followed steps [above](https://github.com/clementine-player/Clementine/issues/6522#issuecomment-714712489) and it worked! No idea why. But the scrobbler be scrobblin'.
